---
title: "Reproducible Research: Peer Assessment 1"
output: html_document

## Loading and preprocessing the data
### 1. Load the data
```{R}
activity <- read.csv("./activity.csv")
```
### 2. Process/transform the data (if necessary) into a format suitable for your analysis
```{R}
activity$date <- as.Date(activity$date,"%Y-%m-%d")
```

## What is mean total number of steps taken per day?
### 1. Make a histogram of the total number of steps taken each day
```{R}
totalstep <- tapply(activity$steps, activity$date, sum)
hist(totalstep)
```

### 2. Calculate and report the mean and median total number of steps taken per day
```{R}
meanstep <- mean(totalstep,na.rm=TRUE)
medianstep <-median(totalstep,na.rm=TRUE)
a <- c(meanstep,medianstep)
a
```

## What is the average daily activity pattern?
### 1. Make a time series plot of the 5-minute interval and the average number of steps taken, averaged across all days 
```{R}
average <- tapply(activity$steps, activity$interval,mean,na.rm=TRUE)
plot(average, type = "l")
title("Average Steps Taken")
```

### 2. Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?
```{R}
names(average[average==max(average)])
```

## Imputing missing values
### 1. Calculate and report the total number of missing values in the dataset 
```{R}
na <- sum(is.na(activity$steps))
na
```
### 2. Devise a strategy for filling in all of the missing values in the dataset. 
### 3. Create a new dataset that is equal to the original dataset but with the missing data filled in.
```{R}
activity2 <- activity
activity2$steps[is.na(activity2$steps)] <- 0
```
### 4. Make a histogram of the total number of steps taken each day and Calculate and report the mean and median total number of steps taken per day. 
```{R}
totalstep2 <- tapply(activity2$steps, activity2$date, sum)
hist(totalstep2)
```
```{R}
meanstep2 <- mean(totalstep2)
medianstep2 <-median(totalstep2)
b <- c(meanstep2,medianstep2)
b
```

## Are there differences in activity patterns between weekdays and weekends?
### 1. Create a new factor variable in the dataset with two levels -- "weekday" and "weekend" indicating whether a given date is a weekday or weekend day.
```{R}
library(lubridate)
activity2$week <- wday(activity2$date)
activity2$week <- factor(activity2$week)
levels(activity2$week) <- list("weekday"=c(2,3,4,5,6),"weekend"=c(1,7))
```
### 2. Make a panel plot containing a time series plot  of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all weekday days or weekend days (y-axis). 
```{R}
s <- split(activity2,activity2$week)
weekday <- s[[1]]
weekend <- s[[2]]
weekday <- tapply(weekday$steps, weekday$interval, mean)
weekend <- tapply(weekend$steps, weekend$interval, mean)

par(mfrow=c(2,1))
plot(weekday, type = "l")
title("Weekday")
plot(weekend, type = "l")
title("Weekend")

```



